import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import { builtinModules } from "module";
import postcss from "postcss";
import atImport from "postcss-import";

const prod = process.argv.includes("--prod");
const targetDir = prod ? null : process.env.OBSIDIAN_PLUGIN_DIR || path.join(process.env.HOME || process.env.USERPROFILE, ". obsidian/plugins/bangumi-obsidian");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

async function buildCss() {
  const inputCss = fs.readFileSync("styles/index.css", "utf8");
  const result = await postcss([atImport()]).process(inputCss, {
    from: "styles/index.css",
    to: "styles.css",
  });
  fs.writeFileSync("styles.css", result.css);
  console.log("✅ CSS built: styles.css");
}

async function main() {
  await buildCss();

  const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["src/main.ts"], // ✅ 修正入口点
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "@codemirror/autocomplete",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/view",
      "@lezer/common",
      "@lezer/highlight",
      "@lezer/lr",
      ...builtinModules,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: prod ? "main.js" : `${targetDir}/main.js`,
    minify: prod,
    plugins: [
      {
        name: "auto-copy-to-obsidian",
        setup(build) {
          build.onEnd(() => {
            if (!prod && targetDir) {
              try {
                if (!fs.existsSync(targetDir)) {
                  fs.mkdirSync(targetDir, { recursive: true });
                }
                if (fs.existsSync("manifest.json")) {
                  fs.copyFileSync("manifest.json", `${targetDir}/manifest.json`);
                }
                if (fs.existsSync("styles.css")) {
                  fs.copyFileSync("styles.css", `${targetDir}/styles.css`);
                }
                console.log("\x1b[32m[Watch] 编译成功，已自动同步至 Obsidian 插件目录\x1b[0m");
              } catch (err) {
                console.error("\x1b[31m[Error] 自动复制文件失败:\x1b[0m", err);
              }
            }
          });
        },
      },
    ],
  });

  if (prod) {
    await context.rebuild();
    await context.dispose();
    console.log("✅ Production build complete");
  } else {
    await context.watch();
    console.log("👀 Watching for changes...");
  }
}

main().catch(err => {
  console.error("❌ Build failed:", err);
  process.exit(1);
});